// Redraws lib/europe.mjs, the holiday map. Only needed to change the area it
// covers (the box below); it is not part of publishing. Run once, from the repo:
//   npm install --no-save world-atlas@2 topojson-client@3 d3-geo@3
//   node scripts/build-map.mjs

import fs from 'fs';
import { feature, mesh } from 'topojson-client';
import { geoMercator, geoPath, geoGraticule } from 'd3-geo';
const res = process.argv[2] || '50m';
const topo = JSON.parse(fs.readFileSync(`node_modules/world-atlas/countries-${res}.json`));
const W = 1000, H = 760;
const box = { type: 'Feature', geometry: { type: 'MultiPoint', coordinates: [[-11.5, 35.2], [26.5, 58.2]] } };
const proj = geoMercator().fitExtent([[0, 0], [W, H]], box);
proj.clipExtent([[-2, -2], [W + 2, H + 2]]);
const path = geoPath(proj).digits(1);
const land = path(feature(topo, topo.objects.land || topo.objects.countries));
const borders = path(mesh(topo, topo.objects.countries, (a, b) => a !== b));
const grat = path(geoGraticule().step([5, 5])());
const k = proj.scale(), [tx, ty] = proj.translate();
const out = `// Europe from Rotterdam's point of view, for the holiday planner: Natural Earth
// ${res} coastlines and borders (public domain, via the world-atlas package),
// projected once with a Mercator fitted to the box below and stored as SVG
// paths, so the page draws a real map without loading tiles or a map library.
// Generated by scripts/build-map.mjs, not hand-edited.
export const W = ${W}, H = ${H};
const K = ${k.toFixed(4)}, TX = ${tx.toFixed(4)}, TY = ${ty.toFixed(4)};
// the same Mercator the paths were drawn with, for placing pins
export const project = (lat, lon) => [TX + K * lon * Math.PI / 180,
  TY - K * Math.log(Math.tan(Math.PI / 4 + (lat * Math.PI / 180) / 2))];
export const LAND = ${JSON.stringify(land)};
export const BORDERS = ${JSON.stringify(borders)};
export const GRID = ${JSON.stringify(grat)};
`;
fs.writeFileSync(new URL('../lib/europe.mjs', import.meta.url), out);
console.log(res, 'bytes', out.length, 'land', land.length, 'borders', borders.length);
// sanity: Rotterdam
const p = proj([4.48, 51.92]); const [x,y]=[tx + k*4.48*Math.PI/180, ty - k*Math.log(Math.tan(Math.PI/4 + 51.92*Math.PI/360))];
console.log('rotterdam', p.map(v=>v.toFixed(2)), x.toFixed(2), y.toFixed(2));
